spring:
  profiles:
    active: dev
  application:
# 注意这里的name影响运行时的输出项目的名称
    name: juanju
    # session失效时间(分钟,两个月),SpringBoot3.0之后不需要再配置store-type
  session:
    timeout: 86400

# redis配置
  data:
    redis:
      port: 6379
      host: localhost
      database: 0


server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain:


mybatis-plus:
  configuration:
#    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.mahua.juanju.controller
  default-flat-param-object: false